#ifndef CVITE_STATUS_H
#define CVITE_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum cvite_status {
    CVITE_STATUS_OK = 0,
    CVITE_STATUS_INVALID_ARGUMENT,
    CVITE_STATUS_OUT_OF_MEMORY,
    CVITE_STATUS_DUPLICATE_SYMBOL,
    CVITE_STATUS_UNKNOWN_SYMBOL,
    CVITE_STATUS_ABI_MISMATCH,
    CVITE_STATUS_LAYOUT_MISMATCH,
    CVITE_STATUS_STALE_GENERATION,
    CVITE_STATUS_INVALID_STATE,
    CVITE_STATUS_INVALID_PACKET,
    CVITE_STATUS_UNSUPPORTED_PROTOCOL,
    CVITE_STATUS_CHECKSUM_MISMATCH,
    CVITE_STATUS_NOT_IMPLEMENTED
} cvite_status;

const char *cvite_status_string(cvite_status status);

#ifdef __cplusplus
}
#endif

#endif
